### ISSUE TITLE
Generated BuildAndPublish.yml doesn't include gitversion

### ISSUE THREAD

**Issue by refactorinc** [GFlisch/Arc4u.Guidance.Doc#165]
**Describe the solution you'd like**
The BuildAndPublish.yml is not configured for gitversion following current guidelines/conventions/agreements
Ideally gitversion is configured for all new projects

**Describe alternatives you've considered**
Doing this manually but it takes time and something else does not get done.

**Comment by rdarko** [comment]
- [ ] Add the flag as false so it activly needs to be enabled and Gitversion.yml file needs to be added to the repository manually
- [ ] with the next version the Gitversion.yml file will be shipped to and the flag will be set to true by default (has to be done after https://github.com/GFlisch/Arc4u.Guidance.Doc/issues/139)

**Comment by HaGGi13** [comment]
As described in the first task of the [previous comment](https://github.com/GFlisch/Arc4u.Guidance.Doc/issues/165#issuecomment-1523364165) the used template parameter list in the hook-in template (`BuildAndPublish.yml`) must be extended by `gitversionEnabled: false`  

Here a more complete example (note the last line):  

```yaml
stages:
- template: Build/BuildAndPublish.yml@templates
  parameters:
    serviceName: MyService
    projectName: MyProject
    folderPrefix: ''
    sonarQubeEnabled: false
    collectCodeCoverage: true
    publishTestResult: false
    publishCodeCoverageResult: false
    gitversionEnabled: false
```
